### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by forumaster** [myriadteam/website#35]
Hi, I saw the myriad website in Italian, and it seems to be translated with google translator, almost all speeches are incorrect, I'm a native Italian, so I can help, you can contact me on bitcointalk if you want help:
https://bitcointalk.org/index.php?topic=1580329

**Comment by cryptapus** [comment]
Pull request is welcome, please offer services at myriadcoin BTCtalk thread or reddit /r/myriadcoin
