### ISSUE TITLE
add yescrypt pool

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myriadteam/website#36]
Could you add the new yescrypt pool (1) to the mining section (2) ?

Thanks

(1) https://www.reddit.com/r/myriadcoin/comments/524h0g/new_pool_mine_myriadcoins_and_unitus_coins_with/?st=isxp07jh&sh=2f1de938
(2) http://myriadcoin.org/en/mining

**Comment by cryptapus** [comment]
Added to master branch. When Unitus integration is complete I'll remove the "beta".
