### ISSUE TITLE
Bad electrum wallet link

### ISSUE THREAD

**Issue by keepmyshirt** [myriadteam/website#86]
Please change to https://github.com/cryptapus/electrum-myr/releases

**Comment by cryptapus** [comment]
Addressed here:

https://github.com/myriadteam/website/pull/82

I don't think it's migrated to the live site yet. AFAIK the test.myriadcoin.org site is not working yet so I've been letting 8bitcoder handle live merges.

**Comment by cryptapus** [comment]
I've tagged 8bitcoder to let us know if we can just merge to live without a test site. I don't have the site details to know if it's safe.

**Comment by cryptapus** [comment]
test site is now functional, live site is updated
